# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bootticket_response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bootticket_response.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x62ootticket_response.proto\"\x14\n\x12\x46irmwareInfoDicepp\"!\n\x0f\x46irmwareInfoTpm\x12\x0e\n\x06ticket\x18\x01 \x01(\x0c\"\x85\x01\n\x1cHubResponseRefreshBootTicket\x12\r\n\x05nonce\x18\x01 \x02(\x0c\x12%\n\x06\x64icepp\x18\x02 \x01(\x0b\x32\x13.FirmwareInfoDiceppH\x00\x12\x1f\n\x03tpm\x18\x03 \x01(\x0b\x32\x10.FirmwareInfoTpmH\x00\x42\x0e\n\x0c\x66irmwareInfo'
)




_FIRMWAREINFODICEPP = _descriptor.Descriptor(
  name='FirmwareInfoDicepp',
  full_name='FirmwareInfoDicepp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=49,
)


_FIRMWAREINFOTPM = _descriptor.Descriptor(
  name='FirmwareInfoTpm',
  full_name='FirmwareInfoTpm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket', full_name='FirmwareInfoTpm.ticket', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=84,
)


_HUBRESPONSEREFRESHBOOTTICKET = _descriptor.Descriptor(
  name='HubResponseRefreshBootTicket',
  full_name='HubResponseRefreshBootTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='HubResponseRefreshBootTicket.nonce', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dicepp', full_name='HubResponseRefreshBootTicket.dicepp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tpm', full_name='HubResponseRefreshBootTicket.tpm', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='firmwareInfo', full_name='HubResponseRefreshBootTicket.firmwareInfo',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=87,
  serialized_end=220,
)

_HUBRESPONSEREFRESHBOOTTICKET.fields_by_name['dicepp'].message_type = _FIRMWAREINFODICEPP
_HUBRESPONSEREFRESHBOOTTICKET.fields_by_name['tpm'].message_type = _FIRMWAREINFOTPM
_HUBRESPONSEREFRESHBOOTTICKET.oneofs_by_name['firmwareInfo'].fields.append(
  _HUBRESPONSEREFRESHBOOTTICKET.fields_by_name['dicepp'])
_HUBRESPONSEREFRESHBOOTTICKET.fields_by_name['dicepp'].containing_oneof = _HUBRESPONSEREFRESHBOOTTICKET.oneofs_by_name['firmwareInfo']
_HUBRESPONSEREFRESHBOOTTICKET.oneofs_by_name['firmwareInfo'].fields.append(
  _HUBRESPONSEREFRESHBOOTTICKET.fields_by_name['tpm'])
_HUBRESPONSEREFRESHBOOTTICKET.fields_by_name['tpm'].containing_oneof = _HUBRESPONSEREFRESHBOOTTICKET.oneofs_by_name['firmwareInfo']
DESCRIPTOR.message_types_by_name['FirmwareInfoDicepp'] = _FIRMWAREINFODICEPP
DESCRIPTOR.message_types_by_name['FirmwareInfoTpm'] = _FIRMWAREINFOTPM
DESCRIPTOR.message_types_by_name['HubResponseRefreshBootTicket'] = _HUBRESPONSEREFRESHBOOTTICKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FirmwareInfoDicepp = _reflection.GeneratedProtocolMessageType('FirmwareInfoDicepp', (_message.Message,), {
  'DESCRIPTOR' : _FIRMWAREINFODICEPP,
  '__module__' : 'bootticket_response_pb2'
  # @@protoc_insertion_point(class_scope:FirmwareInfoDicepp)
  })
_sym_db.RegisterMessage(FirmwareInfoDicepp)

FirmwareInfoTpm = _reflection.GeneratedProtocolMessageType('FirmwareInfoTpm', (_message.Message,), {
  'DESCRIPTOR' : _FIRMWAREINFOTPM,
  '__module__' : 'bootticket_response_pb2'
  # @@protoc_insertion_point(class_scope:FirmwareInfoTpm)
  })
_sym_db.RegisterMessage(FirmwareInfoTpm)

HubResponseRefreshBootTicket = _reflection.GeneratedProtocolMessageType('HubResponseRefreshBootTicket', (_message.Message,), {
  'DESCRIPTOR' : _HUBRESPONSEREFRESHBOOTTICKET,
  '__module__' : 'bootticket_response_pb2'
  # @@protoc_insertion_point(class_scope:HubResponseRefreshBootTicket)
  })
_sym_db.RegisterMessage(HubResponseRefreshBootTicket)


# @@protoc_insertion_point(module_scope)
