# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bootticket_request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bootticket_request.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x62ootticket_request.proto\"\x17\n\x15\x41ttestationInfoDicepp\"\x14\n\x12\x41ttestationInfoTpm\"t\n\x11RefreshBootTicket\x12(\n\x06\x64icepp\x18\x01 \x01(\x0b\x32\x16.AttestationInfoDiceppH\x00\x12\"\n\x03tpm\x18\x02 \x01(\x0b\x32\x13.AttestationInfoTpmH\x00\x42\x11\n\x0f\x61ttestationInfo'
)




_ATTESTATIONINFODICEPP = _descriptor.Descriptor(
  name='AttestationInfoDicepp',
  full_name='AttestationInfoDicepp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=51,
)


_ATTESTATIONINFOTPM = _descriptor.Descriptor(
  name='AttestationInfoTpm',
  full_name='AttestationInfoTpm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=73,
)


_REFRESHBOOTTICKET = _descriptor.Descriptor(
  name='RefreshBootTicket',
  full_name='RefreshBootTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dicepp', full_name='RefreshBootTicket.dicepp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tpm', full_name='RefreshBootTicket.tpm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='attestationInfo', full_name='RefreshBootTicket.attestationInfo',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=75,
  serialized_end=191,
)

_REFRESHBOOTTICKET.fields_by_name['dicepp'].message_type = _ATTESTATIONINFODICEPP
_REFRESHBOOTTICKET.fields_by_name['tpm'].message_type = _ATTESTATIONINFOTPM
_REFRESHBOOTTICKET.oneofs_by_name['attestationInfo'].fields.append(
  _REFRESHBOOTTICKET.fields_by_name['dicepp'])
_REFRESHBOOTTICKET.fields_by_name['dicepp'].containing_oneof = _REFRESHBOOTTICKET.oneofs_by_name['attestationInfo']
_REFRESHBOOTTICKET.oneofs_by_name['attestationInfo'].fields.append(
  _REFRESHBOOTTICKET.fields_by_name['tpm'])
_REFRESHBOOTTICKET.fields_by_name['tpm'].containing_oneof = _REFRESHBOOTTICKET.oneofs_by_name['attestationInfo']
DESCRIPTOR.message_types_by_name['AttestationInfoDicepp'] = _ATTESTATIONINFODICEPP
DESCRIPTOR.message_types_by_name['AttestationInfoTpm'] = _ATTESTATIONINFOTPM
DESCRIPTOR.message_types_by_name['RefreshBootTicket'] = _REFRESHBOOTTICKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AttestationInfoDicepp = _reflection.GeneratedProtocolMessageType('AttestationInfoDicepp', (_message.Message,), {
  'DESCRIPTOR' : _ATTESTATIONINFODICEPP,
  '__module__' : 'bootticket_request_pb2'
  # @@protoc_insertion_point(class_scope:AttestationInfoDicepp)
  })
_sym_db.RegisterMessage(AttestationInfoDicepp)

AttestationInfoTpm = _reflection.GeneratedProtocolMessageType('AttestationInfoTpm', (_message.Message,), {
  'DESCRIPTOR' : _ATTESTATIONINFOTPM,
  '__module__' : 'bootticket_request_pb2'
  # @@protoc_insertion_point(class_scope:AttestationInfoTpm)
  })
_sym_db.RegisterMessage(AttestationInfoTpm)

RefreshBootTicket = _reflection.GeneratedProtocolMessageType('RefreshBootTicket', (_message.Message,), {
  'DESCRIPTOR' : _REFRESHBOOTTICKET,
  '__module__' : 'bootticket_request_pb2'
  # @@protoc_insertion_point(class_scope:RefreshBootTicket)
  })
_sym_db.RegisterMessage(RefreshBootTicket)


# @@protoc_insertion_point(module_scope)
