# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hubresponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hubresponse.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11hubresponse.proto\"\x14\n\x12HubResponseAliasId\"7\n\x16HubResponseAwdtRefresh\x12\x0e\n\x06timeMs\x18\x01 \x02(\r\x12\r\n\x05nonce\x18\x02 \x02(\x0c\"\x17\n\x15HubResponseSensorData\";\n\x11HubResponseUpdate\x12\x17\n\x0fpayloadNumBytes\x18\x01 \x02(\r\x12\r\n\x05nonce\x18\x02 \x02(\x0c\"\xad\x01\n\x19HubResponseCheckForUpdate\x12\r\n\x05nonce\x18\x01 \x02(\x0c\x12:\n\ncomponents\x18\x02 \x03(\x0b\x32&.HubResponseCheckForUpdate.VersionInfo\x1a\x45\n\x0bVersionInfo\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x15\n\rnewestVersion\x18\x02 \x02(\t\x12\x11\n\tissueTime\x18\x03 \x02(\x04\"<\n\x14HubResponseUserInput\x12\x11\n\tavailable\x18\x01 \x02(\x08\x12\x11\n\tuserInput\x18\x02 \x02(\x0c\"\xa2\x02\n\x11SignedHubResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12)\n\x06status\x18\x03 \x02(\x0e\x32\x19.SignedHubResponse.Status\x12%\n\x04type\x18\x04 \x01(\x0e\x32\x17.SignedHubResponse.Type\"\x1a\n\x06Status\x12\x07\n\x03\x41\x43K\x10\x00\x12\x07\n\x03NAK\x10\x01\"{\n\x04Type\x12\x08\n\x04\x41WDT\x10\x00\x12\x0b\n\x07\x41LIASID\x10\x01\x12\x0e\n\nBOOTTICKET\x10\x02\x12\x0b\n\x07REASSOC\x10\x03\x12\x0c\n\x08\x46WUPDATE\x10\x04\x12\x0e\n\nSENSORDATA\x10\x05\x12\x12\n\x0e\x43HECKFORUPDATE\x10\x06\x12\r\n\tUSERINPUT\x10\x07'
)



_SIGNEDHUBRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='SignedHubResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NAK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=564,
  serialized_end=590,
)
_sym_db.RegisterEnumDescriptor(_SIGNEDHUBRESPONSE_STATUS)

_SIGNEDHUBRESPONSE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='SignedHubResponse.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AWDT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALIASID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOOTTICKET', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REASSOC', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FWUPDATE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SENSORDATA', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHECKFORUPDATE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USERINPUT', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=592,
  serialized_end=715,
)
_sym_db.RegisterEnumDescriptor(_SIGNEDHUBRESPONSE_TYPE)


_HUBRESPONSEALIASID = _descriptor.Descriptor(
  name='HubResponseAliasId',
  full_name='HubResponseAliasId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=41,
)


_HUBRESPONSEAWDTREFRESH = _descriptor.Descriptor(
  name='HubResponseAwdtRefresh',
  full_name='HubResponseAwdtRefresh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeMs', full_name='HubResponseAwdtRefresh.timeMs', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='HubResponseAwdtRefresh.nonce', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=98,
)


_HUBRESPONSESENSORDATA = _descriptor.Descriptor(
  name='HubResponseSensorData',
  full_name='HubResponseSensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=123,
)


_HUBRESPONSEUPDATE = _descriptor.Descriptor(
  name='HubResponseUpdate',
  full_name='HubResponseUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payloadNumBytes', full_name='HubResponseUpdate.payloadNumBytes', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='HubResponseUpdate.nonce', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=184,
)


_HUBRESPONSECHECKFORUPDATE_VERSIONINFO = _descriptor.Descriptor(
  name='VersionInfo',
  full_name='HubResponseCheckForUpdate.VersionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HubResponseCheckForUpdate.VersionInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='newestVersion', full_name='HubResponseCheckForUpdate.VersionInfo.newestVersion', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='issueTime', full_name='HubResponseCheckForUpdate.VersionInfo.issueTime', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=360,
)

_HUBRESPONSECHECKFORUPDATE = _descriptor.Descriptor(
  name='HubResponseCheckForUpdate',
  full_name='HubResponseCheckForUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='HubResponseCheckForUpdate.nonce', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='components', full_name='HubResponseCheckForUpdate.components', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_HUBRESPONSECHECKFORUPDATE_VERSIONINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=360,
)


_HUBRESPONSEUSERINPUT = _descriptor.Descriptor(
  name='HubResponseUserInput',
  full_name='HubResponseUserInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='available', full_name='HubResponseUserInput.available', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInput', full_name='HubResponseUserInput.userInput', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=422,
)


_SIGNEDHUBRESPONSE = _descriptor.Descriptor(
  name='SignedHubResponse',
  full_name='SignedHubResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='SignedHubResponse.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='SignedHubResponse.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='SignedHubResponse.status', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='SignedHubResponse.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SIGNEDHUBRESPONSE_STATUS,
    _SIGNEDHUBRESPONSE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=715,
)

_HUBRESPONSECHECKFORUPDATE_VERSIONINFO.containing_type = _HUBRESPONSECHECKFORUPDATE
_HUBRESPONSECHECKFORUPDATE.fields_by_name['components'].message_type = _HUBRESPONSECHECKFORUPDATE_VERSIONINFO
_SIGNEDHUBRESPONSE.fields_by_name['status'].enum_type = _SIGNEDHUBRESPONSE_STATUS
_SIGNEDHUBRESPONSE.fields_by_name['type'].enum_type = _SIGNEDHUBRESPONSE_TYPE
_SIGNEDHUBRESPONSE_STATUS.containing_type = _SIGNEDHUBRESPONSE
_SIGNEDHUBRESPONSE_TYPE.containing_type = _SIGNEDHUBRESPONSE
DESCRIPTOR.message_types_by_name['HubResponseAliasId'] = _HUBRESPONSEALIASID
DESCRIPTOR.message_types_by_name['HubResponseAwdtRefresh'] = _HUBRESPONSEAWDTREFRESH
DESCRIPTOR.message_types_by_name['HubResponseSensorData'] = _HUBRESPONSESENSORDATA
DESCRIPTOR.message_types_by_name['HubResponseUpdate'] = _HUBRESPONSEUPDATE
DESCRIPTOR.message_types_by_name['HubResponseCheckForUpdate'] = _HUBRESPONSECHECKFORUPDATE
DESCRIPTOR.message_types_by_name['HubResponseUserInput'] = _HUBRESPONSEUSERINPUT
DESCRIPTOR.message_types_by_name['SignedHubResponse'] = _SIGNEDHUBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HubResponseAliasId = _reflection.GeneratedProtocolMessageType('HubResponseAliasId', (_message.Message,), {
  'DESCRIPTOR' : _HUBRESPONSEALIASID,
  '__module__' : 'hubresponse_pb2'
  # @@protoc_insertion_point(class_scope:HubResponseAliasId)
  })
_sym_db.RegisterMessage(HubResponseAliasId)

HubResponseAwdtRefresh = _reflection.GeneratedProtocolMessageType('HubResponseAwdtRefresh', (_message.Message,), {
  'DESCRIPTOR' : _HUBRESPONSEAWDTREFRESH,
  '__module__' : 'hubresponse_pb2'
  # @@protoc_insertion_point(class_scope:HubResponseAwdtRefresh)
  })
_sym_db.RegisterMessage(HubResponseAwdtRefresh)

HubResponseSensorData = _reflection.GeneratedProtocolMessageType('HubResponseSensorData', (_message.Message,), {
  'DESCRIPTOR' : _HUBRESPONSESENSORDATA,
  '__module__' : 'hubresponse_pb2'
  # @@protoc_insertion_point(class_scope:HubResponseSensorData)
  })
_sym_db.RegisterMessage(HubResponseSensorData)

HubResponseUpdate = _reflection.GeneratedProtocolMessageType('HubResponseUpdate', (_message.Message,), {
  'DESCRIPTOR' : _HUBRESPONSEUPDATE,
  '__module__' : 'hubresponse_pb2'
  # @@protoc_insertion_point(class_scope:HubResponseUpdate)
  })
_sym_db.RegisterMessage(HubResponseUpdate)

HubResponseCheckForUpdate = _reflection.GeneratedProtocolMessageType('HubResponseCheckForUpdate', (_message.Message,), {

  'VersionInfo' : _reflection.GeneratedProtocolMessageType('VersionInfo', (_message.Message,), {
    'DESCRIPTOR' : _HUBRESPONSECHECKFORUPDATE_VERSIONINFO,
    '__module__' : 'hubresponse_pb2'
    # @@protoc_insertion_point(class_scope:HubResponseCheckForUpdate.VersionInfo)
    })
  ,
  'DESCRIPTOR' : _HUBRESPONSECHECKFORUPDATE,
  '__module__' : 'hubresponse_pb2'
  # @@protoc_insertion_point(class_scope:HubResponseCheckForUpdate)
  })
_sym_db.RegisterMessage(HubResponseCheckForUpdate)
_sym_db.RegisterMessage(HubResponseCheckForUpdate.VersionInfo)

HubResponseUserInput = _reflection.GeneratedProtocolMessageType('HubResponseUserInput', (_message.Message,), {
  'DESCRIPTOR' : _HUBRESPONSEUSERINPUT,
  '__module__' : 'hubresponse_pb2'
  # @@protoc_insertion_point(class_scope:HubResponseUserInput)
  })
_sym_db.RegisterMessage(HubResponseUserInput)

SignedHubResponse = _reflection.GeneratedProtocolMessageType('SignedHubResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDHUBRESPONSE,
  '__module__' : 'hubresponse_pb2'
  # @@protoc_insertion_point(class_scope:SignedHubResponse)
  })
_sym_db.RegisterMessage(SignedHubResponse)


# @@protoc_insertion_point(module_scope)
