# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hubrequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bootticket_request_pb2 as bootticket__request__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hubrequest.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10hubrequest.proto\x1a\x18\x62ootticket_request.proto\"\x1d\n\x0b\x41wdtRefresh\x12\x0e\n\x06timeMs\x18\x04 \x02(\r\"E\n\x11ReassociateDevice\x12\x0c\n\x04uuid\x18\x01 \x02(\x0c\x12\x0c\n\x04\x61uth\x18\x02 \x02(\x0c\x12\x14\n\x0c\x64\x65viceIdCert\x18\x03 \x02(\x0c\"\x1e\n\x0e\x46irmwareUpdate\x12\x0c\n\x04type\x18\x01 \x02(\t\"\"\n\x0b\x41liasIdCert\x12\x13\n\x0b\x63\x65rtificate\x18\x01 \x02(\x0c\"B\n\nSensorData\x12\r\n\x05index\x18\x01 \x02(\r\x12\x13\n\x0btemperature\x18\x02 \x02(\x02\x12\x10\n\x08humidity\x18\x03 \x02(\x02\"$\n\x0e\x43heckForUpdate\x12\x12\n\ncomponents\x18\x01 \x03(\t\"\x19\n\tUserInput\x12\x0c\n\x04type\x18\x01 \x02(\r\"\xe6\x02\n\x11HubRequestMessage\x12\r\n\x05nonce\x18\x01 \x01(\x0c\x12\r\n\x05magic\x18\x02 \x02(\r\x12\x1c\n\x04\x61wdt\x18\x03 \x01(\x0b\x32\x0c.AwdtRefreshH\x00\x12\x1f\n\x07\x61liasid\x18\x04 \x01(\x0b\x32\x0c.AliasIdCertH\x00\x12(\n\nbootTicket\x18\x05 \x01(\x0b\x32\x12.RefreshBootTicketH\x00\x12+\n\rreassocDevice\x18\x06 \x01(\x0b\x32\x12.ReassociateDeviceH\x00\x12#\n\x08\x66wUpdate\x18\x07 \x01(\x0b\x32\x0f.FirmwareUpdateH\x00\x12!\n\nsensorData\x18\x08 \x01(\x0b\x32\x0b.SensorDataH\x00\x12)\n\x0e\x63heckForUpdate\x18\t \x01(\x0b\x32\x0f.CheckForUpdateH\x00\x12\x1f\n\tuserInput\x18\n \x01(\x0b\x32\n.UserInputH\x00\x42\t\n\x07payload\"K\n\x17SignedHubRequestMessage\x12\x0c\n\x04uuid\x18\x01 \x02(\x0c\x12\x0f\n\x07payload\x18\x02 \x02(\x0c\x12\x11\n\tsignature\x18\x03 \x02(\x0c'
  ,
  dependencies=[bootticket__request__pb2.DESCRIPTOR,])




_AWDTREFRESH = _descriptor.Descriptor(
  name='AwdtRefresh',
  full_name='AwdtRefresh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeMs', full_name='AwdtRefresh.timeMs', index=0,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=75,
)


_REASSOCIATEDEVICE = _descriptor.Descriptor(
  name='ReassociateDevice',
  full_name='ReassociateDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='ReassociateDevice.uuid', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auth', full_name='ReassociateDevice.auth', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviceIdCert', full_name='ReassociateDevice.deviceIdCert', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=146,
)


_FIRMWAREUPDATE = _descriptor.Descriptor(
  name='FirmwareUpdate',
  full_name='FirmwareUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='FirmwareUpdate.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=178,
)


_ALIASIDCERT = _descriptor.Descriptor(
  name='AliasIdCert',
  full_name='AliasIdCert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='certificate', full_name='AliasIdCert.certificate', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=214,
)


_SENSORDATA = _descriptor.Descriptor(
  name='SensorData',
  full_name='SensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='SensorData.index', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='SensorData.temperature', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='SensorData.humidity', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=282,
)


_CHECKFORUPDATE = _descriptor.Descriptor(
  name='CheckForUpdate',
  full_name='CheckForUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='components', full_name='CheckForUpdate.components', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=320,
)


_USERINPUT = _descriptor.Descriptor(
  name='UserInput',
  full_name='UserInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UserInput.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=347,
)


_HUBREQUESTMESSAGE = _descriptor.Descriptor(
  name='HubRequestMessage',
  full_name='HubRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='HubRequestMessage.nonce', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magic', full_name='HubRequestMessage.magic', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='awdt', full_name='HubRequestMessage.awdt', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aliasid', full_name='HubRequestMessage.aliasid', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bootTicket', full_name='HubRequestMessage.bootTicket', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reassocDevice', full_name='HubRequestMessage.reassocDevice', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fwUpdate', full_name='HubRequestMessage.fwUpdate', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensorData', full_name='HubRequestMessage.sensorData', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='checkForUpdate', full_name='HubRequestMessage.checkForUpdate', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInput', full_name='HubRequestMessage.userInput', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='HubRequestMessage.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=350,
  serialized_end=708,
)


_SIGNEDHUBREQUESTMESSAGE = _descriptor.Descriptor(
  name='SignedHubRequestMessage',
  full_name='SignedHubRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='SignedHubRequestMessage.uuid', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='SignedHubRequestMessage.payload', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='SignedHubRequestMessage.signature', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=710,
  serialized_end=785,
)

_HUBREQUESTMESSAGE.fields_by_name['awdt'].message_type = _AWDTREFRESH
_HUBREQUESTMESSAGE.fields_by_name['aliasid'].message_type = _ALIASIDCERT
_HUBREQUESTMESSAGE.fields_by_name['bootTicket'].message_type = bootticket__request__pb2._REFRESHBOOTTICKET
_HUBREQUESTMESSAGE.fields_by_name['reassocDevice'].message_type = _REASSOCIATEDEVICE
_HUBREQUESTMESSAGE.fields_by_name['fwUpdate'].message_type = _FIRMWAREUPDATE
_HUBREQUESTMESSAGE.fields_by_name['sensorData'].message_type = _SENSORDATA
_HUBREQUESTMESSAGE.fields_by_name['checkForUpdate'].message_type = _CHECKFORUPDATE
_HUBREQUESTMESSAGE.fields_by_name['userInput'].message_type = _USERINPUT
_HUBREQUESTMESSAGE.oneofs_by_name['payload'].fields.append(
  _HUBREQUESTMESSAGE.fields_by_name['awdt'])
_HUBREQUESTMESSAGE.fields_by_name['awdt'].containing_oneof = _HUBREQUESTMESSAGE.oneofs_by_name['payload']
_HUBREQUESTMESSAGE.oneofs_by_name['payload'].fields.append(
  _HUBREQUESTMESSAGE.fields_by_name['aliasid'])
_HUBREQUESTMESSAGE.fields_by_name['aliasid'].containing_oneof = _HUBREQUESTMESSAGE.oneofs_by_name['payload']
_HUBREQUESTMESSAGE.oneofs_by_name['payload'].fields.append(
  _HUBREQUESTMESSAGE.fields_by_name['bootTicket'])
_HUBREQUESTMESSAGE.fields_by_name['bootTicket'].containing_oneof = _HUBREQUESTMESSAGE.oneofs_by_name['payload']
_HUBREQUESTMESSAGE.oneofs_by_name['payload'].fields.append(
  _HUBREQUESTMESSAGE.fields_by_name['reassocDevice'])
_HUBREQUESTMESSAGE.fields_by_name['reassocDevice'].containing_oneof = _HUBREQUESTMESSAGE.oneofs_by_name['payload']
_HUBREQUESTMESSAGE.oneofs_by_name['payload'].fields.append(
  _HUBREQUESTMESSAGE.fields_by_name['fwUpdate'])
_HUBREQUESTMESSAGE.fields_by_name['fwUpdate'].containing_oneof = _HUBREQUESTMESSAGE.oneofs_by_name['payload']
_HUBREQUESTMESSAGE.oneofs_by_name['payload'].fields.append(
  _HUBREQUESTMESSAGE.fields_by_name['sensorData'])
_HUBREQUESTMESSAGE.fields_by_name['sensorData'].containing_oneof = _HUBREQUESTMESSAGE.oneofs_by_name['payload']
_HUBREQUESTMESSAGE.oneofs_by_name['payload'].fields.append(
  _HUBREQUESTMESSAGE.fields_by_name['checkForUpdate'])
_HUBREQUESTMESSAGE.fields_by_name['checkForUpdate'].containing_oneof = _HUBREQUESTMESSAGE.oneofs_by_name['payload']
_HUBREQUESTMESSAGE.oneofs_by_name['payload'].fields.append(
  _HUBREQUESTMESSAGE.fields_by_name['userInput'])
_HUBREQUESTMESSAGE.fields_by_name['userInput'].containing_oneof = _HUBREQUESTMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['AwdtRefresh'] = _AWDTREFRESH
DESCRIPTOR.message_types_by_name['ReassociateDevice'] = _REASSOCIATEDEVICE
DESCRIPTOR.message_types_by_name['FirmwareUpdate'] = _FIRMWAREUPDATE
DESCRIPTOR.message_types_by_name['AliasIdCert'] = _ALIASIDCERT
DESCRIPTOR.message_types_by_name['SensorData'] = _SENSORDATA
DESCRIPTOR.message_types_by_name['CheckForUpdate'] = _CHECKFORUPDATE
DESCRIPTOR.message_types_by_name['UserInput'] = _USERINPUT
DESCRIPTOR.message_types_by_name['HubRequestMessage'] = _HUBREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['SignedHubRequestMessage'] = _SIGNEDHUBREQUESTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AwdtRefresh = _reflection.GeneratedProtocolMessageType('AwdtRefresh', (_message.Message,), {
  'DESCRIPTOR' : _AWDTREFRESH,
  '__module__' : 'hubrequest_pb2'
  # @@protoc_insertion_point(class_scope:AwdtRefresh)
  })
_sym_db.RegisterMessage(AwdtRefresh)

ReassociateDevice = _reflection.GeneratedProtocolMessageType('ReassociateDevice', (_message.Message,), {
  'DESCRIPTOR' : _REASSOCIATEDEVICE,
  '__module__' : 'hubrequest_pb2'
  # @@protoc_insertion_point(class_scope:ReassociateDevice)
  })
_sym_db.RegisterMessage(ReassociateDevice)

FirmwareUpdate = _reflection.GeneratedProtocolMessageType('FirmwareUpdate', (_message.Message,), {
  'DESCRIPTOR' : _FIRMWAREUPDATE,
  '__module__' : 'hubrequest_pb2'
  # @@protoc_insertion_point(class_scope:FirmwareUpdate)
  })
_sym_db.RegisterMessage(FirmwareUpdate)

AliasIdCert = _reflection.GeneratedProtocolMessageType('AliasIdCert', (_message.Message,), {
  'DESCRIPTOR' : _ALIASIDCERT,
  '__module__' : 'hubrequest_pb2'
  # @@protoc_insertion_point(class_scope:AliasIdCert)
  })
_sym_db.RegisterMessage(AliasIdCert)

SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATA,
  '__module__' : 'hubrequest_pb2'
  # @@protoc_insertion_point(class_scope:SensorData)
  })
_sym_db.RegisterMessage(SensorData)

CheckForUpdate = _reflection.GeneratedProtocolMessageType('CheckForUpdate', (_message.Message,), {
  'DESCRIPTOR' : _CHECKFORUPDATE,
  '__module__' : 'hubrequest_pb2'
  # @@protoc_insertion_point(class_scope:CheckForUpdate)
  })
_sym_db.RegisterMessage(CheckForUpdate)

UserInput = _reflection.GeneratedProtocolMessageType('UserInput', (_message.Message,), {
  'DESCRIPTOR' : _USERINPUT,
  '__module__' : 'hubrequest_pb2'
  # @@protoc_insertion_point(class_scope:UserInput)
  })
_sym_db.RegisterMessage(UserInput)

HubRequestMessage = _reflection.GeneratedProtocolMessageType('HubRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _HUBREQUESTMESSAGE,
  '__module__' : 'hubrequest_pb2'
  # @@protoc_insertion_point(class_scope:HubRequestMessage)
  })
_sym_db.RegisterMessage(HubRequestMessage)

SignedHubRequestMessage = _reflection.GeneratedProtocolMessageType('SignedHubRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDHUBREQUESTMESSAGE,
  '__module__' : 'hubrequest_pb2'
  # @@protoc_insertion_point(class_scope:SignedHubRequestMessage)
  })
_sym_db.RegisterMessage(SignedHubRequestMessage)


# @@protoc_insertion_point(module_scope)
